version : '3.5'
services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - .:/wwwroot
            - ./config/nginx:/etc/nginx/conf.d
        depends_on:
            - web
    web:
        build:
            context: .
            dockerfile: Dockerfile

        command: gunicorn was.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - .:/wwwroot
        expose:
            - "8000"
