version : '3.5'
services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - .:/wwwroot
            - ./config/nginx:/etc/nginx/conf.d
        depends_on:
            - web
    web:
        build:
            context: .
            dockerfile: Dockerfile_with_apm
        environment:
            - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
        command: newrelic-admin run-program gunicorn was.wsgi:application --bind 0.0.0.0:8000
        expose:
            - "8000"
